serverAddr = "openvpn.shubhamtatvamasi.com"
serverPort = 7000

[[proxies]]
name = "openvpn_vpn_upd"
type = "udp"
localPort = 1194
remotePort = 1194

[[proxies]]
name = "openvpn_vpn_tcp"
type = "tcp"
localPort = 1194
remotePort = 1194

[[proxies]]
name = "openvpn_shubhamtatvamasi_com_http"
type = "http"
localPort = 80
customDomains = ["openvpn.shubhamtatvamasi.com"]

[[proxies]]
name = "openvpn_shubhamtatvamasi_com_https"
type = "https"
localPort = 443
customDomains = ["openvpn.shubhamtatvamasi.com"]
